"""add mysql comments"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = "2e10a8c1ee78"
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=mysql.VARCHAR(length=64),
               comment='刷新令牌hash（sha256 hex）',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment='过期时间',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=mysql.DATETIME(),
               comment='注销时间',
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'refresh_tokens',
        '刷新令牌表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码哈希',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'users',
        '用户表',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='用户表',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'refresh_tokens',
        existing_comment='刷新令牌表',
        schema=None
    )
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='注销时间',
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='过期时间',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='刷新令牌hash（sha256 hex）',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###

